name = "Yak Shaver"
license = "MIT"
licenselink = "https://github.com/daosyn/yak-shaver/blob/master/license"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Brandon Dao"
  homepage = "https://daosyn.info"

